README.md, bin/parser.js, lib/parser.js, spec/xmlParser_spec.js
Regarding #10 
Added a boolean option "textNodeConversion".
It is by default `true` to preserve the default behaviour.
=> add option "textNodeConversion"

bin/parser.js, lib/parser.js, spec/xmlParser_spec.js
I migrated some code that parses SVGs from `xml2js` to `fast-xml-parser` and I found that, at one point, I needed to do the following:
```
const shapes = Array.isArray(svg[shapeType]) ? svg[shapeType] : [svg[shapeType]]
shapes.map(...)
```
With `xml2js` even when a shape node was just one, it was returned as an array and the check wasn’t needed.
I’m not sure if this is something you’d like to consider, but it helped in my case. I added a test case, too.
=> Add arrayMode option to parse any nodes as arrays

bin/validator.js, lib/parser.js, spec/assets/crlf.xml, spec/validator_spec.js
Related to https://github.com/NaturalIntelligence/fast-xml-parser/issues/36
In fact, the XML I retrieve from an external API has CRLF line break instead of just LF.
Your regex doesn't handle that case that's why the validator always return `false` (see https://stackoverflow.com/a/10805198/569101)
=> Correctly remove CRLF line breaks

spec/j2x_spec.js, src/j2x.js
This is useful when you are deleting nodes from the JSON and rewriting XML. While I could see a case for writing an empty node in this case (`<b/>`), I'm fairly certain we never want the current behavior which is `<b>undefined</b>`.
so if you have:
```
const obj = {
house: {
pet: [
"cat",
"spider",
"dog"]
}
};
delete obj.house.pet[1]; // get rid of spider!
var result = parser.parse(obj);
```
You get:
```
<house>
<pet>cat</pet>
<pet>undefined</pet>
<pet>dog</pet>
</house>
```
IMO you wanted:
```
<house>
<pet>cat</pet>
<pet>dog</pet>
</house>
```
=> Keep undefined nodes out of the XML output.

package.json, src/parser.d.ts
Some type definitions for external API, attempt to fix #69.
This PR doesn't change anything at runtime, it's only typing support for users use typescript.
It's not yet complete, but it is a start and better than nothing.
A different approach to create a separate typings file would be to convert the whole project to typescript. That would be a pretty big step and would also influence further development workflow, build process etc.
Besides filling the gaps of this type definitions, it might be interesting to provide a second signature to `parse` which takes a generic type. This could then be used as the return value.
Thus, when the developer knows that the parsed XML will be in a certain structure,
It might look something like this, but I didn't try it:
```javascript
export function …
```
=> first draft of typings for typescript #69

package-lock.json, spec/x_cyrillic_2j_str_spec.js, src/x2j.js
Added language option for setting range of characters. It allow use not english language characters only, but also cyrillic. For setting language need to put range into the localeRange variable. By default localeRange is empty string, so regexp will proccesing english based characters only. Let's fill localeRange to procces english and russian characters of XML tags at same time for example: 
const options = {
localeRange:    "a-zA-Zа-яёА-ЯЁ"
}
Fix #87 
[ ]Bug Fix
[x]New Feature
=> Added support of cyrillic characters in parsing XML to JSON

package-lock.json, spec/validator_cyrillic_xml_spec.js, spec/validator_utf8_with_BOM_spec.js, src/parser.d.ts, src/util.js, src/validator.js
Corrected returning value defaultOptions in buildOptions function instead of set every newOptions from defaultOptions in loop when there are not user's options. I think it give a little bit rise of perfomance (fix #89). Fixed bug in validation when XML data with byte order marker (BOM) (fix #90). Added support of non-english characters in XML validation (fix #91).
Enhancement, refactoring, bug fix
[x]Bug Fix
[x]Refactoring / Technology upgrade
[x]New Feature
=> fix #89,fix #90, fix #91 Refactored buildOptions, fixed bug with BOM and added support non-english characters in validator

src/parser.d.ts
Currently the usage of fast-xml-parser with TypeScript is only limited when converting JSON into XML. This is because the TypeScript definition of j2xParser is missing. This PR adds the missing definition.
[X]Bug Fix
[   ]Refactoring / Technology upgrade
[   ]New Feature
=> added missing TypeScript definition for j2xParser

package.json
Fix for issue #112: CLI tools won't work unless `lib/parser.js` is included when installing `fast-xml-parser`.
[x]Bug Fix
[ ]New Feature
=> Adding lib/parser.js to package.json to fix CLI tools

cli.js, package.json
Yesterday, I submitted a PR updating the `package.json` to include some files missing to get the CLI working.  Running the updated code today, I realized there were some other issues, some of which prevented install.  This addresses them.
Apologies for not catching these issues yesterday.
There are some other enhancements I may submit to the CLI tools later, but I first wanted to make sure to fix the issues I created.
[x]Bug Fix
[ ]New Feature
=> CLI Tools fixes, part 2

README.md
- fix bad importer parser (use of `fastXmlParser` instead of `parser`)
- fix indentation
- remove the way to use `parser.js` directly from GitHub (it is served as `text/plain` and can't be parsed by browsers)
Also, please, **please**, :pray:, publish a changelog with **breaking changes** from one version to an other. Or maybe create an UPGRADE.md file to tell people how to upgrade from a previous major version.
It's still related to that issue https://github.com/NaturalIntelligence/fast-xml-parser/issues/35
I spend few hours fixing code while uprgading from 2.8.3.
Some options got renamed (`attrPrefix` => `attributeNamePrefix`), some options disapear (like `ignoreNonTextNodeAttr`), etc.
Also `validate()` function does not return `false` but an object now.
=> Few update to README

index.html, spec/demoapp_spec.js
While I was working on #79 I noticed that if the user changes something on the result textarea, any further Convert or Validate calls did not update the textarea content. The solution for this was quite simple, just had to change all $.text() calls to $.val()
=> Changes on index.html

spec/validator_spec.js, src/validator.js
Bugfix for #129 
When validating XML containing a 'length' attribute currently an error is always returned 'attribute length is repeated.'. 
This is because the code uses an array to check for repeated attributes and calls hasOwnProperty('length'). I have changed this to use an object instead of an array so hasOwnProperty('length') will only return true when there are multiple length attributes. The test I have added verifies this.
[x]Bug Fix
[ ]New Feature
Benchmark results:
```
❯ node benchmark/perfTest3.js
validation : 15075.528720836128 requests/second
xml to json : 13612.412033517821 requests/second
xml to json + json string : 12826.365584690317 requests/second
xml to json string : 2125.6406392103368 …
```
=> Pass validation if XML contains 'length' attribute

spec/stopNodes_spec.js, src/xmlstr2xmlnode.js
This field is an array with 0 or more tagnames. When it encounters a tagname that matches the list of stopNodes, it will treat all the stuff understand this tag as a string.
This is used to support the parsing of certain xml documents where some nodes, such as <description> contains a xhtml structure. We need to treat it as a string and pass it to calling entity.
=> Support a new option "stopNodes".

cli.js
I'd like to use the fast-xml-parser as a pre-commit hook in a project. Currently, the cli only returns exitCode of 0, by making this change, the pre-commit hook fails and forces the user to make the corresponding changes. I don't see any tests for the cli currently so I didn't add one for this PR.
Benchmark results:
node benchmark\perfTest3.js
validation : 10701.291345251915 requests/second
xml to json : 9646.121693327514 requests/second
xml to json + json string : 7912.822290970307 requests/second
xml to json string : 1179.1563269883957 requests/second
xml2js  : 3074.7737447301733 requests/second
**Note** : Please ensure that you've read contribution [guidelines](https://github.com/NaturalIntelligence/fast-xml-parser/blob/m …
=> ValidateOnly now returns exitCode 1 when validation errors are found

spec/validator_spec.js, src/validator.js
When a tag is split into multiple lines, validation fails.
For example
```
<name
attribute1="attribute1"
attribute2="attribute2"
/>
```
is considered invalid.
To solve this issue, I add a check also for new line characters.
=> fix validation for tag on multiple lines

src/parser.d.ts
- Adds the `stopNodes` attribute to the `X2jOptions` in `src/parser.d.ts` so they can be used in typescript projects without the typescript compiler complaining (and ide's can autocomplete them).
Fixes #191
=> bugfix(types): add stopNodes to X2jOptions

src/parser.d.ts
I noticed that while `arrayMode` supports `strict` as an option, the TS typings did not reflect that.
=> Added type support for arrayMode = 'strict'

spec/validator_spec.js
Reach 100% coverage in validator spec
The "else" case of a potential comment was missing
=> Reach 100% coverage in validator spec

spec/validator_spec.js, src/validator.js
=> Validator: Remove redundant space in error message

spec/validator_spec.js, src/validator.js
=> Validator: Fail for stray ampersand characters

spec/validator_utf8_with_BOM_spec.js, spec/x_cyrillic_2j_str_spec.js, src/parser.d.ts, src/util.js, src/validator.js, src/xmlstr2xmlnode.js
Validator: Fix name regexp
The previous implementation only allowed the "localeRange" for the first character, and it did not validate the following characters at all, because the regexp did not include $, so if the first character
matched, the regexp would match.
Replace the regexp with one that matches the [XML spec](https://www.w3.org/TR/xml/#NT-NameStartChar) (except [\u10000-\uEFFFF] which matches digits for some reason...) and match *all* the characters.
Remove the localeRange option, which is no longer needed
=> Validator: Fix name regexp

spec/validator_spec.js
=> Validator: Simplify tests

src/validator.js
=> Validator: Beautify

src/validator.js
With these changes, the library should work in IE11 browsers without ES6 template literals as well.
It fixes issue #238 
=> fix IE11 not supporting ES6 template strings

src/parser.js
We can make IE 11 still works when use npm package. Example a block code on TypeScript:
```typescript
import { J2xOptions, j2xParser } from 'fast-xml-parser';
export function parseObjToXml(obj: any): string {
const defaultOptions: J2xOptions = {
attributeNamePrefix: '@',
attrNodeName: false,
textNodeName: '#text',
ignoreAttributes: false,
cdataTagName: false,
cdataPositionChar: '\\c',
format: true,
indentBy: '  ',
supressEmptyNode: false
};
const inMes = '<?xml version="1.0" encoding="UTF-8"?>\n';
return inMes + new j2xParser(defaultOptions).parse(obj);
}
```
=> Support IE 11 works on TypeScript when used by npm

spec/cdata_spec.js, spec/data_spec.js, src/xmlstr2xmlnode.js
…
```xml
<root><a>1
2
3</a></root>
```
previously parsed as 
```json
{"root":{"a":"1 2\n3"}}
```
instead of
```json
{"root":{"a":"1\n2\n3"}}
```
=> fix(parse): fix parsing of multiline tag data when xml with no whitespaces between tags

package.json, tasks/postinstall.js
`postinstall` scripts tend to be obnoxious when used for advertising, and there are [better methods available](https://docs.npmjs.com/cli/v6/commands/npm-fund). Usually if someone is interested in contributing, they'll seek out projects to contribute to, but `postinstall` scripts are shown on every build resulting in noisy logs that make it harder to debug failing builds.
The nature of `postinstall` means it can't be disabled without risking disabling an actual `postinstall` that is required for a particular package, and any form of check within the script (i.e for an env variable) won't prevent all the noise since the package managers always print the path to the scripts they're running before they run them.
Resolves #236
=> fix: remove `postinstall` script

README.md, spec/arrayMode_spec.js, src/node2json.js, src/parser.d.ts, src/util.js
Enhance the `arrayMode` with RegEx/Callback to be able to control which Tags should be returned as an array.
This feature enables fine grained and correct XML parsing where it's known that some tags only return an array.
See [discussion](https://github.com/NaturalIntelligence/fast-xml-parser/issues/68)
```json
{
"items": [
{"name": "item1"}
]
}
```
Will produce:
```xml
<?xml version="1.0"?>
<items>
<name>item1</name>
</items>
```
That's fine, but if we want to parse it back to same JSON we can now use:
```js
var jsonObj = parser.convertToJson(tObj, {
arrayMode: /items/
});
```
This will produce expected output.
Sometimes RegEx can be complicated, thefore a cb can be used:
```js
var jsonObj = parser.convertToJson(tObj, {
arrayMode: function(tagname) { return tagname === 'items'}
});
``` …
=> feat(arrayMode): support RegEx and function in arrayMode option

spec/data_spec.js, src/xmlstr2xmlnode.js
This is a naive attempt at solving the following issue:
https://github.com/NaturalIntelligence/fast-xml-parser/issues/320
Please note that my experience with this repository is fairly low, so I might have missed something important.
```
validation : 29237.1202899018 requests/second
xml to json : 24875.297773092963 requests/second
xml to json + json string : 22191.624311589047 requests/second
xml to json string : 3994.622584408293 requests/second
xml2js  : 7993.719125817242 requests/second
```
```
validation : 29701.63520998558 requests/second
xml to json : 26255.646131059493 requests/second
xml to json + json string : 22435.547703433473 requests/second
xml to json string : …
```
=> Fix namspaced tag parsing

src/parser.js
On a fresh install off this package whenever I tried to use the parse I would run into a an error 
```
Could not locate module ../src/nimndata mapped as:
/Users/{my project...}/src/$1.
```
I notice that all the other imports in the `parse.js` file use `"./filename"` for imports. So i changed this to match. 
=> Fix Import of nimndata in parser

src/parser.d.ts
Fixes https://github.com/NaturalIntelligence/fast-xml-parser/issues/368 by making `skipLike` optional in the `numParseOptions` for the parser.
=> Make skipLike optional for strnumOptions

spec/xmlParser_spec.js, src/node2json.js, src/parser.d.ts, src/xmlstr2xmlnode.js
This is a feature request for an option that makes the parser return a property for the textNodeName even if there are no attributes or node children. This prevents the downstream consuming JS to require checks for the text node and if it doesn't exist, use the property path itself.
Option would default to false so that the current behavior remains default.
[349](https://github.com/NaturalIntelligence/fast-xml-parser/issues/349)
validation : 22482.344697710287 requests/second
xml to json : 15002.244861535037 requests/second
xml to json + json string : 13868.767986614608 requests/second
xml to json string : 2939.2827347641673 requests/second
xml2js  : 5709.279811841135 requests/second …
=> added alwaysCreateTextNode option to force text node creation

src/fxp.d.ts
The typings defined `parse`, even if the actual class exposes `build`.
Also changing the parameter name from `options` to `jObj`
Improve the experience using XMLBuilder in v4 with Typescript by using the correct function name, `build` instead of `parse`.
This pull request doesn't have an issue connected with it, as it's quite small.
**Expected**:
When using XMLBuilder with Typescript, it should suggest and accept `new Builder(options).build`
**Actual**:
When using XMLBuilder with Typescript, it suggests and accepts `new Builder(options).parse`, which is not defined on the actual class. Attempting to use `new Builder(options).build` raises a Typescript error, and we need to use `// @ts-ignore` to be able to build. 
**Benchmarks**:
Shouldn't affect performance, but just to show that I …
=> Change XMLBuilder typings to expose correct function name

CHANGELOG.md
Just fix the bold on CHANGELOG.md
=> Fix bold on CHANGELOG.md

spec/j2x_spec.js, src/xmlbuilder/json2xml.js
This fixes a bug where JSON elements that have a `#text` property but do not have any attribute properties are written in the XML string having been called against the `tagValueProcessor` twice.
The fix just removes the duplicate `tagValueProcessor` call as this is extraneous and does not cause a regression issue.
Fixes #425;
fxp : 86512.97288990665 requests/second
fxp - preserve order : 173967538.9033842 requests/second
xml2js  : 17897.584436115638 requests/second
Running Suite: XML Builder benchmark
fxp : 89999.27338492977 requests/second
fxp - preserve order : 174703313.43980005 requests/second
xml2js  : 17826.2562878387 requests/second
=> Remove duplicate tag processor call

src/xmlbuilder/orderedJs2Xml.js
Fix #430 to allow library to work in environments where bundler set javascript to strict.
Add missing `let` in `for-in` loop.
=> fix: ReferenceError when Bundled with Strict

spec/stopNodes_spec.js, src/xmlparser/OrderedObjParser.js
When using the `stopNodes` option, if tags with the same name as the stop node are contained in the stop node, we will incorrectly close the stopped node early. This fixes that issue.
Fixes: https://github.com/NaturalIntelligence/fast-xml-parser/issues/455
=> Fix stopNodes when same tag appears inside node

spec/transform_tagname_spec.js, src/fxp.d.ts, src/xmlbuilder/json2xml.js, src/xmlparser/OptionsBuilder.js, src/xmlparser/OrderedObjParser.js
Add an option to transform tag names in output of `.parse`. Option name is:
```
transformTagName: false | (tagName: string) => string;
```
Pasting the test here because it's a great sample of what this PR does:
```
const xmlData = `<?xml version='1.0'?>
<root>
<person>Person 1</person>
<Person>Person 2</Person>
<PERSON>Person 3</PERSON>
<person>Person 4</person>
</root>
`;
const parser = new XMLParser({
ignoreDeclaration: true,
transformTagName: (tagName) => tagName.toLowerCase()
});
let result = parser.parse(xmlData);
const expected = {
"root": {
"person": [
"Person 1",
"Person 2",
"Person 3",
"Person 4"
]
}
};
expect(result).toEqual(expected);```
=> Add transformTagName option to transform tag names when parsing

index.html
TLDR: Demo site was broken due to missing dependency
Demo site for this package is broken, see e.g. https://github.com/NaturalIntelligence/fast-xml-parser/issues/479
This is due to outdated CDN links for the dependency CodeMirror (giving 404 responses). I replaced the broken links for both javascript and CSS files with links to a working CDN.
=> Update CodeMirror CDN Links in index.html

README.md, USERs.md
Prettier no longer uses this repo, see https://github.com/prettier/plugin-xml/blob/main/CHANGELOG.md#030---2019-11-14.
Likewise, NHS Digital does not use this repo in any of its organisations (nhsconnect, NHSDigital, nhsuk, or NHS-digital-website).
=> Remove Prettier and NHS Digital from list of users

docs/v4/4.XMLValidator.md
Fixes a typo of "entites" to "entities"
A separate typo fix from #495
=> Fix entites to entities on XMLValidator doc page

src/fxp.d.ts
value in should be unknown for both and should align with return type same options on the parser config. 
applies to #489 
this allows the representation of dates and other more complex types in tags and attributes without raising type errors for typescript consumers.
* [X ]Bug Fix
=> fix: Builder tag/attributeValueProcessor types

docs/v4/2.XMLparseOptions.md, spec/transform_attributes_spec.js, src/fxp.d.ts, src/xmlbuilder/json2xml.js, src/xmlparser/OptionsBuilder.js, src/xmlparser/OrderedObjParser.js
In my previous PR I added `transformTagName` https://github.com/NaturalIntelligence/fast-xml-parser/pull/469 To keep it consistent I've added a `transformAttributeName` with the same function and signature.
Also included documentation and updated type definitions.
Example:
```js
const parser = new XMLParser({
transformAttributeName: (attr) => attr.toLowerCase()
});
let result = parser.parse(xmlData);
```
=> Add transformAttributeName to transform the attribute name upon parsing

.vscode/settings.json, benchmark/XmlBuilder.js, benchmark/XmlParser.js, spec/j2x_ordered_spec.js, src/xmlbuilder/orderedJs2Xml.js
Improve the indentation behaviour in case of `preserveOrder` as mentioned in issue #520
```txt
$  node XmlBuilder.js
Running Suite: XML Builder benchmark
fxp : 87861.97295953878 requests/second
fxp - preserve order : 85976678.00085683 requests/second
xml2js  : 24993.80134645897 requests/second
$  node XmlParser.js
fxp v3 : 75320.38483930491 requests/second
fxp : 50433.057600239335 requests/second
fxp - preserve order : 54474.10059634518 requests/second
xmlbuilder2 : 19436.208365520688 requests/second
xml2js  : 13894.559475966855 requests/second
```
```txt
$  node XmlBuilder.js
Running Suite: XML Builder benchmark
fxp : 84735.79374909295 requests/second
fxp - preserve order : 79211254.59850551 requests/second
xml2js  : 23660.05480193879 requests/second
$ …
```
=> 520 preserveorder formatting

src/fxp.d.ts
Allow to omit options when creating a XMLBuilder instance
The code allows to pass undefined for options.
=> refactor(types): allow to omit options when creating a XMLBuilder instance

spec/arrayMode_spec.js, src/xmlparser/node2json.js
This is fix for isArray option isn't parsing tags with 0 as value correctly. This only affected when we are parsing tags, not attributes.
The problem is that `obj[options.textNodeName]` is checking the value exist, but if it `false` or `0` it will fail the test.
So you can try to fix it to test it also for boolean type or zero.
The opened issue is #490 
=> IsArray option isn't parsing tags with 0 as value correctly #490

spec/updateTag_spec.js, src/xmlparser/OrderedObjParser.js
Fixes #564 
The `jPath` in `updateTag()` callback for self-closing tags contained a trailing slash (like: `root.a/`) which was not intended and could lead to errors if you implemented logic based on the `jPath` and did not take that into account.
I've added removing trailing slash from `jPath` in the same place where it's removed from `tagName`.
=> Remove trailing slash from jPath for self-closing tags

src/xmlbuilder/json2xml.js
Only set textNodeName, and attributeNamePrefix is empty string, build result is error.
Example：
```js
const schema_obj = {
field: {
values: {
value: {
'#text': 10061001,
size: '5',
},
},
id: 'skuCombineContent',
type: 'multiInput',
},
};
const parse_options = {
ignoreAttributes: false,
attributeNamePrefix: '',
textNodeName: '#text',
};
const builder = new XMLBuilder(parse_options);
const schema_xml = builder.build(schema_obj);
```
Test code: 
```ts
it('xml build test', async () => {
const schema_obj = {
field: {
values: {
value: {
'#text': 10061001,
size: '5',
},
},
id: 'skuCombineContent',
name: 'skuProduct',
type: 'multiInput',
},
};
const parse_options = {
ignoreAttributes: false,
attributeNamePrefix: '',
textNodeName: '#text',
};
const builder = new …
```
=> Only set textNodeName, build xml is error

spec/j2x_spec.js, src/xmlbuilder/json2xml.js
After the fix `null` and `undefined` attributes in the starting object do not cause odd whitespaces and newlines in the built xml, regardless of whether `format` is `true` or `false`. Issue #585 
Perf test on XMLBuilder:
```
Running Suite: XML Builder benchmark
fxp : 76193.36948123561 requests/second
fxp - preserve order : 238552830.29948822 requests/second
xml2js  : 21083.181183955512 requests/second
```
=> Fix for null and undefined attributes when building xml (#585)

spec/stopNodes_spec.js, src/xmlparser/OrderedObjParser.js
The `stopNodes` option currently doesn't work with the `remoteNSPrefix` option. This pull request fixes that issue and adds tests to demonstrate the fix.
=> Fix stopNodes to work with removeNSPrefix (#607)

src/fxp.d.ts
This PR improves typing for `build` and `parse` by making both functions generic.
It also fixes the return type of `build`, which should be `string`.
```ts
// Before
const result = xml.parse(data); // `result` is `any`
// After
type ExpectedObject = {
title: string;
description: string;
};
const result = xml.parse<ExpectedObject>(data); // `result` is `ExpectedObject`
```
```ts
// Before
const xml = builder.build(obj); // `xml` is `any`
// After
const xml = builder.build(obj); // `xml` is `string`
```
=> fix(types): make `build` and `parse` generic

src/xmlbuilder/json2xml.js
If the given object has `null` prototype instead of `Object`, it throws `jObj.hasOwnProperty` error.
`Object.prototype.hasOwnProperty.call(` should be used instead for this kind of objects.
=> Fix `jObj.hasOwnProperty is not a function`

spec/cdata_spec.js, spec/entities_spec.js, src/xmlparser/OrderedObjParser.js
Changes the parsing of CDATA sections to not escape entities.
In other words:
- Before: `<[CDATA[&amp;]]>` -> `&`
- After: `<[CDATA[&amp;]]>` -> `&amp;`
I also added a new test so that this behavior can be tested on its own.
Please note that I did not attempt to avoid any breaking changes here as the issue suggested, but if it is desired, I would be happy to gate this fix behind a new option.
The contents of a CDATA section will also now be run through `tagValueProcessor` even when the `cdataPropName` option is provided. I am unsure as to if this inconsistency was intentional (the code that would have made it consistent seems to have been commented out a while ago), so if that is considered an unrelated change, I would also be happy to split it out into a separate PR.
Closes #632.
Before: …
=> Don't escape entities in CDATA sections

docs/v4/5.Entities.md, spec/entities_spec.js, src/v5/EntitiesParser.js, src/v5/valueParsers/EntitiesParser.js, src/xmlparser/OrderedObjParser.js
This PR adds a `htmlNumericEntities` option which adds support for parsing HTML numeric entities.
```
fxp v3 : 43885.453114704054 requests/second
fxp : 28444.884306095257 requests/second
fxp - preserve order : 35582.44370634719 requests/second
xmlbuilder2 : 12279.374624117605 requests/second
xml2js  : 17997.982194339696 requests/second
```
```
fxp v3 : 56829.18072321323 requests/second
fxp : 35711.03397186936 requests/second
fxp - preserve order : 35048.53534051172 requests/second
xmlbuilder2 : 12565.714384084644 requests/second
xml2js  : 17898.357168570532 requests/second
```
=> Add support for parsing HTML numeric entities

spec/validator_spec.js, src/validator.js
Fixes https://github.com/NaturalIntelligence/fast-xml-parser/issues/620
`fxparser -V a.xml` with input.xml.
```
</html>
```
On current master.
```
if (tagName !== otg.tagName) {
^
TypeError: Cannot read property 'tagName' of undefined
at Object.exports.validate (/Users/ryosukefukatani/work/fast-xml-parser/src/validator.js:108:33)
at callback (/Users/ryosukefukatani/work/fast-xml-parser/src/cli/cli.js:51:29)
at /Users/ryosukefukatani/work/fast-xml-parser/src/cli/cli.js:78:9
at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```
With this change.
```
{
err: {
code: 'InvalidTag',
msg: "Closing tag 'html' has not been opened.",
line: 1,
col: 1
}
}
```
**Note** : Please ensure that you've read contribution …
=> fix: validator bag when closing tag is not opened.

docs/v5/1. Getting Started.md, docs/v5/5. ValueParsers.md
There are typos in the v5 documents: `fast-xml-parse` should be `fast-xml-parser`.
https://github.com/NaturalIntelligence/fast-xml-parser/blob/a96b96807207bdde0c4ce6cc31841fda936b4000/docs/v5/1.%20Getting%20Started.md?plain=1#L6-L9
Relevant error message:
```sh
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/fast-xml-parse: Not Found - 404
fast-xml-parse is not in the npm registry, or you have no permission to fetch it.
```
So I found and corrected similar typos from v5 document.
=> docs: fix typos in v5 document `fast-xml-parse`

spec/j2x_spec.js, src/xmlbuilder/json2xml.js
If I have `oneListGroup` enabled I would expect that:
```json
{
"a": ["(first)", "second"]
}
```
Would give me:
```xml
<a>(first)(second)</a>
```
But I get:
```xml
<a>
<a>(first)</a>
<a>(second)</a>
</a>
```
This commit fixes that issue.
=> fix: get oneListGroup to work as expected for array of strings

docs/v4/2.XMLparseOptions.md, docs/v4/3.XMLBuilder.md, spec/attrIgnore_spec.js, src/fxp.d.ts, src/ignoreAttributes.js, src/xmlbuilder/json2xml.js, src/xmlparser/OrderedObjParser.js
Introduce a new feature that allows to selectively ignore XML attributes during parsing or building, based on an array of strings, regular expressions, or a callback function. No breaking changes, the old values `ignoreAttributes: true` and `ignoreAttributes: false` are processed same way as before.
Implements [Issue #666](https://github.com/NaturalIntelligence/fast-xml-parser/issues/666).
=> feat #666: add selective ignoreAttributes by pattern or callback

src/v5/XmlPartReader.js
Fix a parsing bug for v5.
would parse to:
instead of (now):
=> Fix empty tag key name for v5

src/xmlparser/DocTypeReader.js
Fixes issue [698](https://github.com/NaturalIntelligence/fast-xml-parser/issues/698) that results in a reference error of `entityName is not defined` being raised when run in strict mode - such as when using via an esm module import.
=> Fixes entity parsing when used in strict mode

spec/j2x_spec.js, src/xmlbuilder/json2xml.js
During XML building, CDATA with null value is not handled properly. When a value is null, the cdata property is ignored and treated as a normal node.
This PR aims to resolve this issue (#700) by handling the cdata property when it has a null value.
```
Running Suite: XML Builder benchmark
fxp : 73911.77177576702 requests/second
fxp - preserve order : 96821055.83555794 requests/second
xml2js  : 23993.824078178754 requests/second
```
```
Running Suite: XML Builder benchmark
fxp : 71796.8171188612 requests/second
fxp - preserve order : 95102276.51741566 requests/second
xml2js  : 22884.60165181542 requests/second
```
**Note** : Please ensure that you've read contribution [guidelines](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/CONTRIBUT …
=> Fix node generation when a cdata property is null

src/xmlparser/OrderedObjParser.js
To improve XML parsing performance by optimizing leaf node detection in OrderedObjParser.
When parsing XML documents, the parser frequently needs to check if a node is a leaf node. The current implementation creates unnecessary temporary arrays during this check, which impacts performance especially for large XML files.
The optimization changes how we check for leaf nodes:
```diff
- isLeafNode = Object.keys(currentNode.child).length === 0
+ isLeafNode = currentNode.child.length === 0
```
This is safe because:
- `child` is explicitly initialized as an array in XmlNode constructor
- Array modifications only happen through controlled methods (`add` and `addChild`)
- Array's `length` property is read-only and cannot be corrupted
- Hardware: MacBook Pro M1
- Node.js: v19.6.1
- OS: macOS
- …
=> perf: Optimize leaf node detection by using direct array length access

src/cli/cli.js
Modify emitted CLI standard output to be valid JSON. `console.log(object)` is insufficient with nested input structure. Addresses #709 .
=> fix: emit full JSON string from CLI when no output filename specified

package.json
The `package.json` file didn't declare a "files" attribute, so default files were included, but not the files in the lib folder (which includes CommonJS resources)
Closes #713
I have run npm pack with the new configuration to verify that the content is the same as in https://www.npmjs.com/package/fast-xml-parser/v/5.0.1?activeTab=code and includes the lib folder.
=> fix: include CommonJS resources in the npm package

src/cli/cli.js
The output json will no longer be formatted as a single string when no CLI flags are specified.
fixes #711 
=> #711 Removed string formating on cli output

spec/entities_spec.js, src/v6/EntitiesParser.js, src/v6/valueParsers/EntitiesParser.js, src/xmlparser/OrderedObjParser.js
Numeric entities over U+FFFF would be truncated to their lower two bytes due to use of `String.fromCharCode` which only returns a UTF-16 single code unit. Replacing the relevant calls with `String.fromCodePoint` addresses the problem. (See [caniuse.com](https://caniuse.com/mdn-javascript_builtins_string_fromcodepoint) for compatibility.)
Fixes #725.
[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for …
=> fix: support numeric entities with values over 0xFFFF

benchmark/README.md, benchmark/XmlBuilder.mjs, benchmark/XmlParser.mjs, benchmark/package.json, benchmark/try.mjs, docs/CONTRIBUTING.md
- move files from .js to .mjs so they are usable as modules
- shim __dirname using fileURLToPath
- add a benchmark/README.md explaining the build process (such as it is)
- update CONTRIBUTING.md to link to the new README.md
- fix backslashes in CONTRIBUTING.md
The benchmark wasn't usable or documented.
Fixes: #730
=> fix: update benchmark so it's buildable

package.json
This enables bundlers like webpack to perform better tree-shaking.
Closes #733
=> chore: declare package as side-effect free

src/fxp.d.ts
It exports the types in fxp.d.ts to make them easily usable.
This change is related to the closed issue, which I'm also experiencing -> https://github.com/NaturalIntelligence/fast-xml-parser/issues/736
=> Export types in fxp.d.ts
