NaturalIntelligence/fast-xml-parser

bin/parser.js
lib/parser.js
spec/xmlParser_spec.js

Allow wrap attributes with subobject to compatible with other parsers output

---

.travis.yml
cli.js
lib/read.js
package.json

xml2js: Accept standard input

---

README.md

just some spelling corrections.
Thanks for creating fxp!
Please specify here what you're planning to achieve by this pull request and how it can help in regard of this work-space. 
If it is a bug fix, please mention the issue number. If there is no issue has been raised but the PR directly then it should follow the template given to raise the issue. Like input, expected output, actual output etc.
[ ]Bug Fix
[ ]New Feature
**Note** : Please ensure that you've read contribution [guidelines](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/CONTRIBUTING.md) before raising this PR.

fix some typos in readme

---

package.json

This removes the unused lodash dependency. Closes #157.
**Note** : Please ensure that you've read contribution [guidelines](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/CONTRIBUTING.md) before raising this PR.

Remove unused lodash dependency

---

.github/pull_request_template.md

Fix broken link in PR template

---

README.md

Have 1 mistype less in documentation

fix: correct misspelled word in readme

---

src/xmlstr2xmlnode.js

fix(compare): generic perfomance improve

---

README.md

fix: broken contributing.md link in readme

---

spec/arrayWithExtendedPrototypeProps_spec.js
src/node2json.js

Fix parsing array with extnended prototype

---

docs/CONTRIBUTING.md
docs/v4/1.GettingStarted.md

Help by clarifying the readmes and fixing an example in the v4 getting started example code.
I can run the performance tests mentioned in the contributing doc, but I figured since this is only README updates it wouldn't be necessary. I am not sure what to check on the Type below, maybe a new "Doc Update" box could be added to the template?
[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further …

fix 2 small typos in readmes

---

index.html

Fixing XML validator from demo page.

Fix xml validator from demo page

---

src/fxp.d.ts

As per Issue description, closes #489

Fix "tagValueProcessor" type definition

---

README.md

Clarify what is meant by this bullet point - for instance, is this a pure JS implementation, or not?
As far as my teammate @mike-lang and I can tell, this repo is fully JavaScript.  However, because the bullet says "Faster than any pure JS implementation", it makes us wonder if this library is NOT a pure JS implementation.
I think the intent of this bullet point is to say this is faster than any other pure JS implementation that you know of - agreed?  
And can you confirm this is indeed a pure JS implementation?
Thanks!

Clarify speed claim about pure JS implementation in README

---

README.md

Update `require` in node project example to use package

docs: fix node project example

---

docs/v4/2.XMLparseOptions.md

Fixed typo in 2.XMLparseOptions.md

---

src/xmlparser/DocTypeReader.js

After the security fix this code was left over

Remove unused code

---

docs/v4/2.XMLparseOptions.md
docs/v4/6.HTMLParsing.md
index.html
spec/html_spec.js

This is just a cosmetic follow-up on the discussion #693

use XML instead of XMl

---

README.md

Some references remained about the former v5 which is now v6.

docs(README): mention v5 instead of v4

---

.github/workflows/node.js.yml

The version was missing in the range from 14 to 22.

ci: build with Node 18.x

---

src/fxp.d.ts

Fix typo in types
